# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20161014_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Candidate',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='Poll',
            new_name='poll',
        ),
    ]
